spring:
    application:
        name: news
    datasource:
        password: 1643
        url: jdbc:postgresql://localhost:5432/news
        username: postgres
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
        enabled: true
    cache:
        type: redis
        redis:
            host: localhost
            port: 6379
    servlet:
        multipart:
            enabled: true

    cloud:
        openfeign:
            circuitbreaker:
                enabled: true

server:
    port: 8083

upload:
    dir: C:\Users\Asus\Desktop\FileDirectory